language: node_js
node_js: "10"
env:
  global:
    - AWS_BUCKET_QA_ADDRESS=s3://bucket-front-end-qa
    - AWS_BUCKET_PRODUCTION_ADDRESS=s3://bucket-front-end-production
install:
  - npm install
script:
  - npm test
after_success:
  - if [ "$TRAVIS_BRANCH" = "qa" && "$TRAVIS_PULL_REQUEST" = "false" ]; then ./publish.qa.sh; fi
  - if [ "$TRAVIS_BRANCH" = "production" && "$TRAVIS_PULL_REQUEST" = "false" ]; then ./publish.production.sh; fi